addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
before_install:
  - sudo apt-get update
  - sudo apt-get install g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 20
language: cpp
compiler: g++
script: make
