addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
before_install:
  - sudo apt-get update
  - sudo apt-get install g++-7
  - g++ --version
language: cpp
compiler: g++
script: make
